hana-harmoney/frontend

src/app/api/_/proxy/[...path]/route.ts, src/app/api/auth/login/route.ts, src/app/auth/login/page.tsx, src/components/auth/loginForm.tsx, src/components/common/inputWithLabel.tsx, src/components/common/navbar/BottomNav.tsx, src/lib/api/client.ts, src/middlewares.ts
#9 
로그인 화면을 구현하고 API 프록시를 설정했습니다.
어떤 변경 사항이 있나요?
화면명 | 설명 | 이미지
---|---|---
로그인 화면 | 로그인 화면입니다 | <img width="489" height="597" alt="스크린샷 2025-08-25 오전 11 24 02" src="https://github.com/user-attachments/assets/481ce5ed-13fa-4ae7-8dbb-b55725006170" />
API 호출할 때 apiClient를 통해서 호출해야 프록시 거쳐서 헤더에 토큰이 들어갑니다.
=> [#9] feat: 로그인 화면 구현

src/app/globals.css
- #12 
피그마에 맞게 global.css 색상 수정했습니다.
어떤 변경 사항이 있나요?
=> [#12] style: 피그마에 맞게 global.css 색상 수정

src/app/api/auth/login/route.ts, src/app/api/proxy/[...path]/route.ts, src/app/chat/layout.tsx, src/app/chat/page.tsx, src/components/chat/ChatProfileImage.tsx, src/components/chat/ChatRoomTile.tsx, src/lib/api/chat.ts, src/lib/api/client.ts, src/lib/date/dateformatter.ts, src/stores/useChatRoomsStore.ts, src/types/apiResponse.ts, src/types/chatRoom.ts, src/types/jobs.ts
- #6
채팅방 목록 화면 구현했습니다.
어떤 변경 사항이 있나요?
화면명 | 설명 | 이미지
---|---|---
채팅방 목록 화면 | 채팅방 목록 화면입니다. | <img width="490" height="608" alt="image" src="https://github.com/user-attachments/assets/ad914b17-713e-4863-a1e9-b33cc682a778" />
=> [#6] feat: 채팅 목록 화면 구현 및 API 연동

src/app/auth/signup/layout.tsx, src/app/auth/signup/route.ts, src/app/auth/signup/step1/page.tsx, src/app/auth/signup/step2/page.tsx, src/app/auth/signup/step3/page.tsx, src/app/globals.css, src/components/common/bottomButton.tsx, src/components/common/navbar/BottomNav.tsx, src/components/ui/datepicker.tsx, src/stores/userRegisterStore.ts
- #10
어떤 변경 사항이 있나요?
<table>
<tr>
<td align="center">
<b>Step 1</b><br/>기본정보 입력 (이름, 생년월일, 성별)
</td>
<td align="center">
<b>Step 2</b><br/>로그인 정보 입력 (아이디, 비밀번호)
</td>
<td align="center">
<b>Step 3</b><br/>약관 동의 및 가입 완료
</td>
</tr>
</table>
bottomButton 컴포넌트 생성해놓았습니다
=> [#10] feat: 회원가입 온보딩 구현

src/app/jobs/new/location/page.tsx
- #27
구직 글 등록시 장소 선택하는 부분에 주소 검색창 추가했습니다
어떤 변경 사항이 있나요?
|주소검색 버튼|주소검색 모달 창|
|--|--|
|<img width="292" height="641" alt="image" src="https://github.com/user-attachments/assets/ad7889a3-7a8d-49e9-920b-99478d6fa48f" /> |<img width="293" height="645" alt="image" src="https://github.com/user-attachments/assets/eb418097-62e1-4e75-81db-ac4512b1bb8e" /> |
=> [#27] feat: 구직 글 등록시 주소 검색창 추가

src/app/jobs/[id]/page.tsx
- #29
구직 글 종료시 글 상세 disable 버튼 [종료된 공고입니다] 처리
boardData의 status가 1일때 disable 처리했습니다~
어떤 변경 사항이 있나요?
=> [#29] feat: 구직 글 종료시 disable button

src/app/profile/page.tsx
#34 
- 탈퇴 처리 부분 토스트 메시지 수정
어떤 변경 사항이 있나요?
=> [#34] feat: 탈퇴 처리 메시지 수정

src/app/globals.css, src/app/home/page.tsx, src/lib/api/home.ts, src/types/pocket.ts
- #35 
홈 화면 주머니 조회 API 연동 및 CSS 수정했습니다.
어떤 변경 사항이 있나요?
=> [feat] 홈 화면 계좌 정보 불러오기 API 연동

src/app/jobs/[id]/page.tsx, src/app/jobs/page.tsx, src/types/jobs.ts
#40 
- 이미지 비율 수정 및 내 글일 경우 채팅/전화 버튼 안보임 + 내 글일 경우에만 수정/삭제 보이도록
어떤 변경 사항이 있나요?
=> [#40] feat: 내 글 관련 처리

src/app/chat/page.tsx, src/app/chatroom/[roomId]/page.tsx, src/app/chatroom/[roomId]/pocket/layout.tsx, src/app/chatroom/[roomId]/pocket/page.tsx, src/app/jobs/[id]/page.tsx, src/components/chat/ChatMessageList.tsx, src/hooks/useAccount.ts, src/hooks/useChatMessages.ts, src/lib/api/chat.ts
- #47 
채팅방 관련 에러 수정, 채팅방 빈화면 처리, 채팅방 생성 기능 추가
어떤 변경 사항이 있나요?
=> [feat] 채팅 에러 수정, 빈화면 처리, 채팅방 생성 기능 추가

src/app/jobs/[id]/edit/location/page.tsx, src/app/jobs/[id]/edit/page.tsx, src/app/jobs/[id]/page.tsx, src/app/profile/edit/page.tsx, src/components/common/header.tsx, src/lib/api/jobs.ts, src/stores/useJobEditStore.ts
- #57 
- 게시글 수정 페이지 추가 및 API 연동
어떤 변경 사항이 있나요?
화면명 | 설명 | 이미지
---|---|---
게시글 수정 페이지 | 등록 페이지 재활용 - 기존 정보를 전역변수화 | <img width="340" height="721" alt="image" src="https://github.com/user-attachments/assets/a77b16d0-5a1a-4827-b911-bc5ea16dc165" />
=> [feat] 게시글 수정 페이지 추가 및 API 연동

src/app/home/account/page.tsx, src/app/home/pocket/[id]/page.tsx, src/app/home/pocket/new/page.tsx, src/components/home/History.tsx, src/lib/api/pocket.ts, src/lib/groupHistoryByDay.ts, src/lib/toDisplayHistory.ts, src/lib/utils.ts, src/types/accountDetail.ts, src/types/home.ts, src/types/pocket.ts
- #53 
- 주머니 생성, 삭제 API 연동
- 주머니 상세조회 API 연동
- 상세조회시 필요한 데이터 처리 함수 분리 및 수정
- groupHistoryByDay.ts : 거래내역 데이터 날짜 별로 묶는 함수
- toDisplayHistory.ts: 시간표시, 입출금 표시, 거래 상대 데이터 처리함수
어떤 변경 사항이 있나요?
=> [feat] 주머니 관련 API 연동

src/app/jobs/[id]/page.tsx, src/app/profile/[id]/page.tsx, src/components/ui/datepicker.tsx
- #68 
- 게시글 페이지 : 사용자 신용도 형식 수정
- datepicker readonly 형식을 추가하여 입력 방지
어떤 변경 사항이 있나요?
=> [fix] 신용도 형식 수정 및 datepicker 수정

package.json, public/firebase-messaging-sw.js, public/service-worker.js, src/app/NotificationProvider.tsx, src/app/home/page.tsx, src/app/layout.tsx, src/firebase/index.ts, src/lib/api/fcm.ts, src/lib/fcm.ts
- #75 
- FCM 관련 설정 추가
- FCM 토큰 발급 및 등록 요청
- FCM 서비스 워커 등록 구현
- 알림 요청 구현
어떤 변경 사항이 있나요?
=> [feat] FCM 연동

src/app/jobs/new/location/page.tsx
- #81 
- 게시글 등록 주소 선택 모달 닫기 버튼 겹치는 현상 해결
어떤 변경 사항이 있나요?
=> [fix]: 다이얼로그 버튼 겹치는 현상 해결

src/components/chat/ChatPocketCard.tsx, src/types/pocket.ts
- #92 
주머니로 옮기기 화면에서 목표까지 남은 금액 표시
어떤 변경 사항이 있나요?
화면명 | 설명 | 이미지
---|---|---
주머니로 옮기기 미선택 | == | <img width="497" height="343" alt="스크린샷 2025-09-03 오후 2 03 30" src="https://github.com/user-attachments/assets/28037499-b7ce-4adc-a37a-11e59b783e4b" />
주머니로 옮기기 선택 | == | <img width="498" height="362" alt="스크린샷 2025-09-03 오후 2 03 37" src="https://github.com/user-attachments/assets/065edaac-d93f-4110-a3f5-cc0a2e5c2d2a" />
=> [design] 주머니로 옮기기 화면에서 목표까지 남은 금액 표시

src/app/asset/page.tsx
- #98 
- 자산 페이지 수입 / 지출 합계 값 추가
어떤 변경 사항이 있나요?
화면명 | 설명 | 이미지
---|---|---
자산 페이지 | 합계 추가 | <img width="386" height="678" alt="image" src="https://github.com/user-attachments/assets/a66483cd-3d05-43d6-a21f-731438e037ee" />
=> [#98] feat: 수입/지출 내역 합계 추가

src/components/pocket/PocketCompleteLottie.tsx
- close #104 
박수 애니메이션에 자산 이동 탭 버튼 추가
어떤 변경 사항이 있나요?
화면명 | 설명 | 이미지
---|---|---
목표 달성 애니메이션 | 자산탭으로 이동하는 버튼 추가 | <img width="216" height="468" alt="스크린샷 2025-09-04 오후 1 38 50" src="https://github.com/user-attachments/assets/76b2fbcb-6d99-4e47-9c9e-166119cec6a6" />
=> [feat] 박수 애니메이션에 자산 이동 탭 버튼 추가

src/app/home/account/[accountId]/page.tsx, src/app/home/page.tsx, src/app/profile/delegate/page.tsx, src/app/profile/delegate/pages/DelegatePage.tsx
- close #106 
빌드 시 나는 오류를 해결했습니다.
프로필 대리 작성 페이지 useSearchParam 제거
계좌 상세 페이지 useSearchParam 제거
어떤 변경 사항이 있나요?
=> [fix] 빌드 오류 해결

src/app/api/auth/login/route.ts
- close #108 
로그인 시 쿠키 sameSite 설정 none으로 변경
어떤 변경 사항이 있나요?
=> [fix] 로그인 시 쿠키 sameSite 설정 none으로 변경
